# Experimentation with a theme
#remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- github-pages
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Site settings
title: Monitoring Main Mission
email: ""
author: Stephen Michael Kellat
lang: en-us
description: > # this means to ignore newlines until "baseurl:"
  Macro-blogging by Stephen Michael Kellat
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kellat.me" # the base hostname & protocol for your site
# twitter_username: writer_smk
github_username:  skellat
telegram_username: smkellat
twitch_username: shameraider
masto_username: alpacaherder
liberapay_username: smkellat
ko_fi_username: smkellat
wikipedia_username: Smk

permalink: /:year/:title.html

# We can go ahead and show excerpts on the home page
show_excerpts: true

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['forceout', 'ChangeLog', 'CNAME', 'README.md', 'CODE_OF_CONDUCT.md', 'CONTRIBUTING.md', 'SECURITY.md', 'LICENSE', 'docs', 'Gemfile.lock', 'Gemfile', .post-template', '_drafts', '.github', 'add-blog-post.sh']

# Timezone

timezone: America/Detroit

