# Site settings
title: Yet Another Blogging Attempt
email: ashtabulaecv197@gmail.com
author: Stephen Michael Kellat
lang: en-us
description: > # this means to ignore newlines until "baseurl:"
  This is yet another blogging attempt made by Stephen Michael Kellat.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kellat.me" # the base hostname & protocol for your site
twitter_username: writer_smk
github_username:  skellat

permalink: /:year/:title.html

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['forceout', 'ChangeLog', 'CNAME', 'README.md', 'CODE_OF_CONDUCT.md', 'CONTRIBUTING.md', 'SECURITY.md', 'LICENSE', 'docs', 'Gemfile.lock', 'Gemfile']

# Timezone

timezone: America/Detroit