site_name: The Web Site of Stephen Michael Kellat
theme: readthedocs
locale: en
site_url: https://kellat.me/
site_description: The main public website of Erie Looking Productions
site_author: Stephen Michael Kellat
repo_url: https://github.com/skellat/new-blog-post-tweety
repo_name: GitHub
remote_branch: master
docs_dir: page
site_dir: docs
copyright: Copyright © 2019-2025 Stephen Michael Kellat.  
plugins: []
markdown_extensions:
  - smarty
  - toc:
      permalink: true
  - sane_lists
nav:
     - Home: index.md
